//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RrepositoryClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManagerSet()
        {
            this.SaleInfoSet = new HashSet<SaleInfoSet>();
        }
    
        public int ManagerID { get; set; }
        public string ManagerName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleInfoSet> SaleInfoSet { get; set; }
    }
}
